name: CI/CD Security Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scans:
    name: Run Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run SAST with Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"

      - name: Run SCA with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          ignore-unfixed: true
          exit-code: 1
          severity: "CRITICAL,HIGH"

      - name: Run Secret Scanning with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: ".gitleaks.toml"

      - name: Run DAST with OWASP ZAP
        uses: zaproxy/action-full-scan@v0.5.0
        with:
          target: "http://localhost:5000"
